import Reveal from "@/components/shared/Reveal";
import Section from "@/components/ui/Section";
import {
  HandshakeIcon,
  UserCircleIcon,
  ShieldCheckIcon,
  RobotIcon,
  FileTextIcon,
  LockIcon,
  CreditCardIcon,
  SignOutIcon,
  ScalesIcon,
  ArrowClockwiseIcon,
} from "@/components/ui/icons";
import type { IconProps } from "@phosphor-icons/react";
import type { ComponentType } from "react";

interface TermSection {
  id: string;
  num: string;
  title: string;
  Icon: ComponentType<IconProps>;
  body: string[];
  list?: string[];
  note?: string;
  span?: string;
}

const SECTIONS: TermSection[] = [
  {
    id: "acceptance",
    num: "01",
    title: "Acceptance of terms",
    Icon: HandshakeIcon,
    body: [
      "By initializing your CarbonSynqEarth account or deploying our tracking SDKs, you agree to comply with these terms, all applicable environmental laws, and international reporting standards.",
      "If you do not agree with any of these terms, your license to access our proprietary AI modules is automatically revoked.",
    ],
  },
  {
    id: "eligibility",
    num: "02",
    title: "Eligibility & ESG responsibility",
    Icon: UserCircleIcon,
    body: [
      "The platform is intended for use by corporate entities and authorized representatives aged 18 or older. Users represent that they possess the legal authority to commit their organization to targets.",
    ],
    note: "Access to Net-Zero Alpha requires corporate sustainability credential verification, to keep the underlying data honest.",
  },
  {
    id: "governance",
    num: "03",
    title: "Account governance",
    Icon: ShieldCheckIcon,
    body: [
      "You are responsible for maintaining the confidentiality of your ESG credentials. CarbonSynqEarth uses AES-256 encryption for all data at rest.",
    ],
    list: [
      "Multi-factor authentication required",
      "Raw data accuracy is the user's responsibility",
      "Scope 1, 2, and 3 emissions reporting",
      "Regular security audits and logs",
    ],
  },
  {
    id: "ai-ethics",
    num: "04",
    title: "AI usage & ethical boundaries",
    Icon: RobotIcon,
    body: [
      "You agree to use the CarbonSynqEarth AI engine solely for legitimate carbon footprint analysis. Reverse-engineering our CarbonPulse algorithms, or using our data to train competing models, is prohibited. AI-generated insights are recommendations, and should be verified by sustainability professionals.",
    ],
  },
  {
    id: "proprietary",
    num: "05",
    title: "Content & carbon credits",
    Icon: FileTextIcon,
    body: [
      "All reporting templates, ESG frameworks, and dynamic visualizations generated by CarbonSynqEarth are the sole intellectual property of the company.",
    ],
    note: "Carbon credits purchased through our integrated marketplace are subject to market fluctuations and regulatory changes.",
  },
  {
    id: "security",
    num: "06",
    title: "Security & data governance",
    Icon: LockIcon,
    body: [
      "CarbonSynqEarth adheres to SOC 2 and GDPR compliance standards. Your operational data is siloed and never used for cross-tenant analytics without anonymization.",
      "We reserve the right to audit the data pipeline connected to our platform, to verify certifications and prevent greenwashing.",
    ],
  },
  {
    id: "billing",
    num: "07",
    title: "Subscription & carbon-neutral billing",
    Icon: CreditCardIcon,
    body: [
      "Fees for Enterprise and Pro tiers are billed monthly. Failure to maintain an active subscription results in tracking suspension.",
    ],
    note: "Billing is digital-only, to hold our own transactions to a 0.02kg carbon efficiency target.",
  },
  {
    id: "termination",
    num: "08",
    title: "Termination",
    Icon: SignOutIcon,
    body: [
      "We may terminate or suspend your account and bar access to the service immediately, without prior notice or liability, at our sole discretion, including for breach of these terms.",
    ],
  },
  {
    id: "disputes",
    num: "09",
    title: "Disputes & governing law",
    Icon: ScalesIcon,
    body: [
      "This agreement is governed by the laws of the Republic of India, and is subject to the exclusive jurisdiction of the courts in Bangalore, India.",
    ],
  },
  {
    id: "changes",
    num: "10",
    title: "Changes to these terms",
    Icon: ArrowClockwiseIcon,
    body: [
      "We reserve the right to modify these terms at any time. Material revisions will be provided with at least 30 days' notice before the new terms take effect.",
    ],
  },
];

function TermCard({ section, delay }: { section: TermSection; delay: number }) {
  const { id, num, title, Icon, body, list, note, span } = section;

  return (
    <Reveal delay={delay} className={`${span ?? ""} h-full`}>
      <div
        id={id}
        className="group relative flex h-full flex-col scroll-mt-[100px] overflow-hidden rounded-[20px] border border-black/[0.07] bg-white p-[26px] transition-all duration-500 hover:-translate-y-[3px] hover:border-[#0b3b38]/30 hover:shadow-[0_24px_56px_rgba(11,59,56,0.12)] md:p-[30px]"
      >
        {/* dark green top rule */}
        <span className="absolute inset-x-0 top-0 h-[2px] origin-left scale-x-0 bg-gradient-to-r from-[#0b3b38] via-[#0d4f4b] to-[#188f8b] transition-transform duration-500 group-hover:scale-x-100" />

        {/* hover sheen */}
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(130%_70%_at_50%_-10%,rgba(11,59,56,0.07),transparent_70%)] opacity-0 transition-opacity duration-500 group-hover:opacity-100" />

        <div className="relative flex items-start justify-between">
          <span className="flex h-[46px] w-[46px] items-center justify-center rounded-[14px] border border-[#0b3b38]/15 bg-[#0b3b38]/[0.05] text-[#0d4f4b] transition-all duration-500 group-hover:border-[#0b3b38] group-hover:bg-[#0b3b38] group-hover:text-white">
            <Icon size={20} weight="duotone" />
          </span>
          <span className="pt-[2px] text-[11px] font-semibold tracking-[0.18em] text-[#0b3b38]/35 transition-colors duration-500 group-hover:text-[#0b3b38]">
            {num}
          </span>
        </div>

        <h3 className="relative mt-[24px] font-display text-[23px] leading-[1.15] tracking-[-0.35px] text-[#0b1f1e] md:text-[25px]">
          {title}
        </h3>

        <div className="relative mt-[14px] flex flex-col gap-[12px]">
          {body.map((p, j) => (
            <p key={j} className="text-[13.5px] leading-[1.6] tracking-[-0.1px] text-[#7c8f8d]">
              {p}
            </p>
          ))}

          {list && (
            <ul className="grid grid-cols-1 gap-[8px] pt-[4px] sm:grid-cols-2">
              {list.map((item) => (
                <li key={item} className="flex items-start gap-[10px] text-[13px] leading-[1.5] tracking-[-0.1px] text-[#7c8f8d]">
                  <span className="mt-[6px] h-[4px] w-[4px] shrink-0 rounded-full bg-[#188f8b]" />
                  {item}
                </li>
              ))}
            </ul>
          )}

          {note && (
            <div className="mt-[4px] rounded-[14px] border border-[#188f8b]/15 bg-[#188f8b]/[0.05] px-[16px] py-[14px]">
              <p className="text-[13px] leading-[1.6] tracking-[-0.1px] text-[#166b68]">
                {note}
              </p>
            </div>
          )}
        </div>
      </div>
    </Reveal>
  );
}

export default function TermsOfService() {
  return (
    <>
      {/* HERO */}
      <Section id="terms-hero" narrow className="relative isolate overflow-hidden">
        <div className="pointer-events-none absolute inset-0 -z-10" aria-hidden>
          <div className="absolute inset-0 bg-[radial-gradient(120%_90%_at_18%_0%,#ffffff_0%,#f4faf9_48%,#e6f3f2_100%)]" />
          <div
            className="absolute inset-0 opacity-50"
            style={{
              backgroundImage:
                "linear-gradient(rgba(24,143,139,0.05) 1px, transparent 1px), linear-gradient(90deg, rgba(24,143,139,0.05) 1px, transparent 1px)",
              backgroundSize: "88px 88px",
              maskImage: "radial-gradient(75% 65% at 50% 38%, black, transparent)",
              WebkitMaskImage: "radial-gradient(75% 65% at 50% 38%, black, transparent)",
            }}
          />
        </div>
        <Reveal>
          <div className="flex max-w-[720px] flex-col items-start text-left">
            <span className="mb-[28px] inline-flex items-center gap-[10px] rounded-full border border-black/[0.06] bg-white/70 py-[8px] pr-[18px] pl-[14px] text-[11px] font-semibold uppercase tracking-[0.16em] text-[#3f5a55] shadow-[0_2px_12px_rgba(16,74,71,0.05)] backdrop-blur-md">
              <span className="relative flex h-[7px] w-[7px]">
                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-[#188f8b] opacity-60" />
                <span className="relative inline-flex h-[7px] w-[7px] rounded-full bg-[#188f8b]" />
              </span>
              Legal
            </span>

            <h1 className="font-display text-[44px] leading-[1.05] tracking-[-1px] text-[#0b1f1e] md:text-[64px]">
              Terms of service
            </h1>

            <p className="mt-[24px] max-w-[560px] text-[17px] leading-[1.55] tracking-[-0.2px] text-[#5f706e] md:text-[19px]">
              Our commitment to transparency and sustainable growth &mdash;
              everything you need to know about partnering with CarbonSynqEarth.
            </p>

            <div className="mt-[28px] flex items-center gap-[12px]">
              <span className="rounded-full border border-[#188f8b]/20 bg-[#188f8b]/[0.07] px-[12px] py-[5px] text-[11px] font-semibold uppercase tracking-[0.12em] text-[#188f8b]">
                v3.2
              </span>
              <span className="text-[12px] font-medium tracking-[-0.1px] text-[#92a5a3]">
                Last updated: September 2026
              </span>
            </div>
          </div>
        </Reveal>
      </Section>

      {/* TERMS GRID */}
      <Section id="terms-body" narrow className="relative isolate pt-[0]!">
        <Reveal>
          <div className="mb-[32px] h-px w-full bg-gradient-to-r from-[#188f8b]/60 via-[#188f8b]/20 to-transparent" />
          <span className="mb-[20px] block text-[14px] font-semibold uppercase tracking-[0.18em] text-[#188f8b]">
            What&rsquo;s inside
          </span>
          <h2 className="mb-[48px] max-w-[640px] font-display text-[40px] leading-[0.95] tracking-[-1.28px] text-black md:mb-[56px] md:text-[56px]">
            The fine print, made clear
          </h2>
        </Reveal>

        <div className="grid grid-cols-1 gap-[14px] sm:grid-cols-2 lg:grid-cols-3">
          {SECTIONS.map((section, i) => (
            <TermCard
              key={section.id}
              section={section}
              delay={(i % 3) * 0.08}
            />
          ))}
        </div>
      </Section>
    </>
  );
}
