import Reveal from "@/components/shared/Reveal";
import Section from "@/components/ui/Section";

const sections = [
  {
    id: "acceptance",
    title: "Acceptance of terms",
    body: [
      "By initializing your CarbonSynqEarth account or deploying our tracking SDKs, you agree to comply with these terms, all applicable environmental laws, and international reporting standards.",
      "If you do not agree with any of these terms, your license to access our proprietary AI modules is automatically revoked.",
    ],
  },
  {
    id: "eligibility",
    title: "Eligibility & ESG responsibility",
    body: [
      "The platform is intended for use by corporate entities and authorized representatives aged 18 or older. Users represent that they possess the legal authority to commit their organization to targets.",
    ],
    note: "Access to Net-Zero Alpha requires corporate sustainability credential verification, to keep the underlying data honest.",
  },
  {
    id: "governance",
    title: "Account governance",
    body: [
      "You are responsible for maintaining the confidentiality of your ESG credentials. CarbonSynqEarth uses AES-256 encryption for all data at rest.",
    ],
    list: [
      "Multi-factor authentication required",
      "Raw data accuracy is the user's responsibility",
      "Scope 1, 2, and 3 emissions reporting",
      "Regular security audits and logs",
    ],
  },
  {
    id: "ai-ethics",
    title: "AI usage & ethical boundaries",
    body: [
      "You agree to use the CarbonSynqEarth AI engine solely for legitimate carbon footprint analysis. Reverse-engineering our CarbonPulse algorithms, or using our data to train competing models, is prohibited. AI-generated insights are recommendations, and should be verified by sustainability professionals.",
    ],
  },
  {
    id: "proprietary",
    title: "Content & carbon credits",
    body: [
      "All reporting templates, ESG frameworks, and dynamic visualizations generated by CarbonSynqEarth are the sole intellectual property of the company.",
    ],
    note: "Carbon credits purchased through our integrated marketplace are subject to market fluctuations and regulatory changes.",
  },
  {
    id: "security",
    title: "Security & data governance",
    body: [
      "CarbonSynqEarth adheres to SOC 2 and GDPR compliance standards. Your operational data is siloed and never used for cross-tenant analytics without anonymization.",
      "We reserve the right to audit the data pipeline connected to our platform, to verify certifications and prevent greenwashing.",
    ],
  },
  {
    id: "billing",
    title: "Subscription & carbon-neutral billing",
    body: [
      "Fees for Enterprise and Pro tiers are billed monthly. Failure to maintain an active subscription results in tracking suspension.",
    ],
    note: "Billing is digital-only, to hold our own transactions to a 0.02kg carbon efficiency target.",
  },
  {
    id: "termination",
    title: "Termination",
    body: [
      "We may terminate or suspend your account and bar access to the service immediately, without prior notice or liability, at our sole discretion, including for breach of these terms.",
    ],
  },
  {
    id: "disputes",
    title: "Disputes & governing law",
    body: [
      "This agreement is governed by the laws of the Republic of India, and is subject to the exclusive jurisdiction of the courts in Bangalore, India.",
    ],
  },
  {
    id: "changes",
    title: "Changes to these terms",
    body: [
      "We reserve the right to modify these terms at any time. Material revisions will be provided with at least 30 days' notice before the new terms take effect.",
    ],
  },
];

export default function TermsOfService() {
  
  return (
    <>
      {/* HERO */}
      <Section id="terms-hero" narrow className="relative isolate overflow-hidden text-center">
        <div className="pointer-events-none absolute inset-0 -z-10" aria-hidden>
          <div className="absolute top-1/2 left-1/2 h-[560px] w-[820px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-[radial-gradient(ellipse_at_center,rgba(24,143,139,0.06),transparent_70%)]" />
        </div>
        <Reveal>
          <h1 className="mx-auto max-w-[720px] font-display text-[34px] leading-[1.15] tracking-[-0.5px] text-black md:text-[52px]">
            Terms of service
          </h1>
          <p className="mx-auto mt-[20px] max-w-[520px] text-[15px] leading-[1.6] tracking-[-0.14px] text-[#848484] md:text-[17px]">
            Our commitment to transparency and sustainable growth &mdash;
            everything you need to know about partnering with CarbonSynqEarth.
          </p>
          <p className="mt-[16px] text-[13px] tracking-[-0.14px] text-[#848484]/70">
            Legal framework v3.2
          </p>
        </Reveal>
      </Section>

      {/* TERMS SECTIONS */}
      <Section id="terms-body" narrow className="relative isolate">
        <Reveal>
          <div className="mx-auto max-w-[720px] divide-y divide-black/[0.06]">
            {sections.map((s, i) => (
              <div key={s.id} id={s.id} className="scroll-mt-[100px] py-[36px] first:pt-0">
                <div className="flex items-baseline gap-[14px]">
                  <span className="font-display text-[13px] text-[#188f8b]">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <h2 className="font-display text-[20px] tracking-[-0.3px] text-black md:text-[22px]">
                    {s.title}
                  </h2>
                </div>

                <div className="mt-[14px] space-y-[12px] pl-[27px]">
                  {s.body.map((p, j) => (
                    <p
                      key={j}
                      className="max-w-[620px] text-[15px] leading-[1.7] tracking-[-0.14px] text-[#4a4a4a]"
                    >
                      {p}
                    </p>
                  ))}

                  {s.list && (
                    <ul className="grid grid-cols-1 gap-[8px] pt-[4px] md:grid-cols-2">
                      {s.list.map((item) => (
                        <li
                          key={item}
                          className="flex items-start gap-[10px] text-[14px] leading-[1.5] tracking-[-0.14px] text-[#4a4a4a]"
                        >
                          <span className="mt-[7px] h-[4px] w-[4px] shrink-0 rounded-full bg-[#188f8b]" />
                          {item}
                        </li>
                      ))}
                    </ul>
                  )}

                  {s.note && (
                    <p className="max-w-[620px] rounded-[14px] bg-[#188f8b]/[0.06] px-[16px] py-[12px] text-[14px] leading-[1.6] tracking-[-0.14px] text-[#166b68]">
                      {s.note}
                    </p>
                  )}
                </div>
              </div>
            ))}
          </div>
        </Reveal>
      </Section>
    </>
  );
}