import Reveal from "@/components/shared/Reveal";
import Section from "@/components/ui/Section";
import {
  ShieldCheckIcon,
  LockIcon,
  RobotIcon,
  DatabaseIcon,
  FingerprintIcon,
  ChartPieSliceIcon,
  TruckIcon,
  CookieIcon,
  ListChecksIcon,
  ClockCounterClockwiseIcon,
  ScalesIcon,
} from "@/components/ui/icons";
import type { IconProps } from "@phosphor-icons/react";
import type { ComponentType } from "react";

interface PolicySection {
  id: string;
  num: string;
  title: string;
  Icon: ComponentType<IconProps>;
  body: string[];
  list?: string[];
  note?: string;
  span?: string;
}

const SECTIONS: PolicySection[] = [
  {
    id: "ai-governance",
    num: "02",
    title: "AI governance",
    Icon: RobotIcon,
    body: [
      "Our AI engine, CarbonPulse, follows a strict set of rules before any automated insight reaches you:",
    ],
    list: [
      "Isolated compute — each calculation runs in a temporary container that's destroyed once the task completes.",
      "Human-verified logic — every automated decarbonization strategy is reviewed by an ESG specialist before publication.",
      "No-recall training — our base models are never fine-tuned on user-specific data or supply chain identifiers.",
    ],
  },
  {
    id: "collection",
    num: "03",
    title: "What we collect",
    Icon: DatabaseIcon,
    body: [
      "Primary inputs include:",
    ],
    list: [
      "Direct manual entries",
      "IoT telemetry streams",
      "Utility API integrations",
    ],
    note: "Unlike a shared multi-tenant database, each customer's environmental records sit in a dedicated, encrypted partition.",
  },
  {
    id: "biometrics",
    num: "04",
    title: "Biometric login",
    Icon: FingerprintIcon,
    body: [
      "When you use Face ID or a fingerprint to sign in, we never store the biometric itself. We store a mathematical hash generated by your device's secure enclave — we can't reconstruct your biometrics from it, and your identity stays on your hardware.",
    ],
  },
  {
    id: "usage",
    num: "05",
    title: "How we use it",
    Icon: ChartPieSliceIcon,
    body: [
      "Your data powers two core functions:",
    ],
    list: [
      "ESG analytics — raw energy data becomes CO2e figures, using global warming potential factors from the IPCC Sixth Assessment Report.",
      "Internal benchmarking — comparing departments or sites to flag high-emission clusters and suggest efficiency upgrades.",
    ],
  },
  {
    id: "supply-chain",
    num: "06",
    title: "Supply chain data",
    Icon: TruckIcon,
    body: [
      "Managing Scope 3 emissions without compromising a supplier's own privacy:",
    ],
    list: [
      "Vendor anonymization — when a vendor shares data with you, we strip anything that could identify their specific facilities, leaving only carbon intensity scores.",
      "Explicit consent only — vendors approve each data request individually. There's no automated pulling of supplier data without verified consent.",
    ],
  },
  {
    id: "cookies",
    num: "07",
    title: "Cookies & tracking",
    Icon: CookieIcon,
    body: [
      "We keep tracking minimal. Here's the full inventory:",
    ],
    note: "We don't run marketing trackers. No third-party ad pixels, no cross-site profiling.",
  },
  {
    id: "rights",
    num: "08",
    title: "Your rights",
    Icon: ListChecksIcon,
    body: [
      "Depending on your jurisdiction, you have the following rights over your data:",
    ],
    list: [
      "EU (GDPR): portability, erasure, restrict processing",
      "US (CCPA/CPRA): opt out of sale, correction, limit sensitive use",
    ],
  },
  {
    id: "history",
    num: "09",
    title: "Policy history",
    Icon: ClockCounterClockwiseIcon,
    body: [
      "We maintain a transparent record of all policy changes:",
    ],
    note: "v5.1.2 (May 2026) — Enhanced biometric security. v5.0.0 (Mar 2026) — AI ethics & DPDP compliance. v4.8.0 (Dec 2025) — Standard contractual clauses.",
  },
  {
    id: "legal",
    num: "10",
    title: "Arbitration & governance",
    Icon: ScalesIcon,
    body: [
      "Disputes about this policy that can't be settled directly go to binding arbitration under the rules of the International Chamber of Commerce.",
    ],
    note: "Jurisdiction: Noida, Uttar Pradesh. Language: English / Hindi.",
  },
];

function PolicyCard({ section, delay }: { section: PolicySection; delay: number }) {
  const { id, num, title, Icon, body, list, note, span } = section;

  return (
    <Reveal delay={delay} className={`${span ?? ""} h-full`}>
      <div
        id={id}
        className="group relative flex h-full flex-col scroll-mt-[100px] overflow-hidden rounded-[20px] border border-black/[0.07] bg-white p-[26px] transition-all duration-500 hover:-translate-y-[3px] hover:border-[#0b3b38]/30 hover:shadow-[0_24px_56px_rgba(11,59,56,0.12)] md:p-[30px]"
      >
        {/* dark green top rule */}
        <span className="absolute inset-x-0 top-0 h-[2px] origin-left scale-x-0 bg-gradient-to-r from-[#0b3b38] via-[#0d4f4b] to-[#188f8b] transition-transform duration-500 group-hover:scale-x-100" />

        {/* hover sheen */}
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(130%_70%_at_50%_-10%,rgba(11,59,56,0.07),transparent_70%)] opacity-0 transition-opacity duration-500 group-hover:opacity-100" />

        <div className="relative flex items-start justify-between">
          <span className="flex h-[46px] w-[46px] items-center justify-center rounded-[14px] border border-[#0b3b38]/15 bg-[#0b3b38]/[0.05] text-[#0d4f4b] transition-all duration-500 group-hover:border-[#0b3b38] group-hover:bg-[#0b3b38] group-hover:text-white">
            <Icon size={20} weight="duotone" />
          </span>
          <span className="pt-[2px] text-[11px] font-semibold tracking-[0.18em] text-[#0b3b38]/35 transition-colors duration-500 group-hover:text-[#0b3b38]">
            {num}
          </span>
        </div>

        <h3 className="relative mt-[24px] font-display text-[23px] leading-[1.15] tracking-[-0.35px] text-[#0b1f1e] md:text-[25px]">
          {title}
        </h3>

        <div className="relative mt-[14px] flex flex-col gap-[12px]">
          {body.map((p, j) => (
            <p key={j} className="text-[13.5px] leading-[1.6] tracking-[-0.1px] text-[#7c8f8d]">
              {p}
            </p>
          ))}

          {list && (
            <ul className="space-y-[10px] pt-[4px]">
              {list.map((item) => (
                <li key={item} className="flex items-start gap-[10px] text-[13px] leading-[1.55] tracking-[-0.1px] text-[#7c8f8d]">
                  <span className="mt-[6px] h-[4px] w-[4px] shrink-0 rounded-full bg-[#188f8b]" />
                  {item}
                </li>
              ))}
            </ul>
          )}

          {note && (
            <div className="mt-[4px] rounded-[14px] border border-[#188f8b]/15 bg-[#188f8b]/[0.05] px-[16px] py-[14px]">
              <p className="text-[13px] leading-[1.6] tracking-[-0.1px] text-[#166b68]">
                {note}
              </p>
            </div>
          )}
        </div>
      </div>
    </Reveal>
  );
}

export default function PrivacyPolicy() {
  return (
    <>
      {/* HERO */}
      <Section id="privacy-hero" narrow className="relative isolate overflow-hidden">
        <div className="pointer-events-none absolute inset-0 -z-10" aria-hidden>
          <div className="absolute inset-0 bg-[radial-gradient(120%_90%_at_18%_0%,#ffffff_0%,#f4faf9_48%,#e6f3f2_100%)]" />
          <div
            className="absolute inset-0 opacity-50"
            style={{
              backgroundImage:
                "linear-gradient(rgba(24,143,139,0.05) 1px, transparent 1px), linear-gradient(90deg, rgba(24,143,139,0.05) 1px, transparent 1px)",
              backgroundSize: "88px 88px",
              maskImage: "radial-gradient(75% 65% at 50% 38%, black, transparent)",
              WebkitMaskImage: "radial-gradient(75% 65% at 50% 38%, black, transparent)",
            }}
          />
        </div>
        <Reveal>
          <div className="flex max-w-[720px] flex-col items-start text-left">
            <span className="mb-[28px] inline-flex items-center gap-[10px] rounded-full border border-black/[0.06] bg-white/70 py-[8px] pr-[18px] pl-[14px] text-[11px] font-semibold uppercase tracking-[0.16em] text-[#3f5a55] shadow-[0_2px_12px_rgba(16,74,71,0.05)] backdrop-blur-md">
              <span className="relative flex h-[7px] w-[7px]">
                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-[#188f8b] opacity-60" />
                <span className="relative inline-flex h-[7px] w-[7px] rounded-full bg-[#188f8b]" />
              </span>
              Your data
            </span>

            <h1 className="font-display text-[44px] leading-[1.05] tracking-[-1px] text-[#0b1f1e] md:text-[64px]">
              Privacy policy
            </h1>

            <p className="mt-[24px] max-w-[560px] text-[17px] leading-[1.55] tracking-[-0.2px] text-[#5f706e] md:text-[19px]">
              How CarbonSynq Earth collects, protects, and uses data &mdash;
              explained plainly, with no fine print you have to hunt for.
            </p>

            <div className="mt-[28px] flex items-center gap-[12px]">
              <span className="rounded-full border border-[#188f8b]/20 bg-[#188f8b]/[0.07] px-[12px] py-[5px] text-[11px] font-semibold uppercase tracking-[0.12em] text-[#188f8b]">
                v5.1.2
              </span>
              <span className="text-[12px] font-medium tracking-[-0.1px] text-[#92a5a3]">
                Last updated: May 2026
              </span>
            </div>
          </div>
        </Reveal>
      </Section>

      {/* MISSION */}
      <Section id="mission" narrow className="relative isolate pt-[0]!">
        <Reveal>
          <div className="mb-[32px] h-px w-full bg-gradient-to-r from-[#188f8b]/60 via-[#188f8b]/20 to-transparent" />
          <span className="mb-[20px] block text-[14px] font-semibold uppercase tracking-[0.18em] text-[#188f8b]">
            01 &mdash; Our approach
          </span>
          <h2 className="mb-[20px] max-w-[640px] font-display text-[40px] leading-[0.95] tracking-[-1.28px] text-black md:text-[56px]">
            Our approach to privacy
          </h2>
          <p className="mb-[32px] max-w-[560px] text-[16px] leading-[1.5] tracking-[-0.14px] text-[#848484] md:text-[18px]">
            Privacy isn&rsquo;t a feature we bolted on &mdash; it&rsquo;s how the platform is built.
            CarbonSynqEarth acts as a secure vault for your ESG data, not a shared warehouse.
          </p>
        </Reveal>

        <div className="grid grid-cols-1 gap-[14px] sm:grid-cols-2">
          <Reveal delay={0.08} className="h-full">
            <div className="group relative flex h-full flex-col overflow-hidden rounded-[20px] border border-black/[0.07] bg-white p-[26px] transition-all duration-500 hover:-translate-y-[3px] hover:border-[#0b3b38]/30 hover:shadow-[0_24px_56px_rgba(11,59,56,0.12)] md:p-[30px]">
              <span className="absolute inset-x-0 top-0 h-[2px] origin-left scale-x-0 bg-gradient-to-r from-[#0b3b38] via-[#0d4f4b] to-[#188f8b] transition-transform duration-500 group-hover:scale-x-100" />
              <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(130%_70%_at_50%_-10%,rgba(11,59,56,0.07),transparent_70%)] opacity-0 transition-opacity duration-500 group-hover:opacity-100" />
              <div className="relative flex items-start justify-between">
                <span className="flex h-[46px] w-[46px] items-center justify-center rounded-[14px] border border-[#0b3b38]/15 bg-[#0b3b38]/[0.05] text-[#0d4f4b] transition-all duration-500 group-hover:border-[#0b3b38] group-hover:bg-[#0b3b38] group-hover:text-white">
                  <ShieldCheckIcon size={20} weight="duotone" />
                </span>
                <span className="pt-[2px] text-[11px] font-semibold tracking-[0.18em] text-[#0b3b38]/35 transition-colors duration-500 group-hover:text-[#0b3b38]">
                  A
                </span>
              </div>
              <h3 className="relative mt-[24px] font-display text-[23px] leading-[1.15] tracking-[-0.35px] text-[#0b1f1e] md:text-[25px]">
                Data sovereignty
              </h3>
              <p className="relative mt-[10px] text-[13.5px] leading-[1.55] tracking-[-0.1px] text-[#7c8f8d]">
                You retain full ownership of your data. We provide the infrastructure to process it &mdash; we never claim rights to your raw information.
              </p>
            </div>
          </Reveal>
          <Reveal delay={0.16} className="h-full">
            <div className="group relative flex h-full flex-col overflow-hidden rounded-[20px] border border-[#188f8b]/15 bg-[#f2faf9] p-[26px] transition-all duration-500 hover:-translate-y-[3px] hover:border-[#188f8b]/25 hover:shadow-[0_24px_56px_rgba(11,59,56,0.12)] md:p-[30px]">
              <span className="absolute inset-x-0 top-0 h-[2px] origin-left scale-x-0 bg-gradient-to-r from-[#0b3b38] via-[#0d4f4b] to-[#188f8b] transition-transform duration-500 group-hover:scale-x-100" />
              <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(130%_70%_at_50%_-10%,rgba(11,59,56,0.07),transparent_70%)] opacity-0 transition-opacity duration-500 group-hover:opacity-100" />
              <div className="relative flex items-start justify-between">
                <span className="flex h-[46px] w-[46px] items-center justify-center rounded-[14px] border border-[#188f8b]/20 bg-[#188f8b]/[0.08] text-[#188f8b] transition-all duration-500 group-hover:border-[#188f8b] group-hover:bg-[#188f8b] group-hover:text-white">
                  <LockIcon size={20} weight="duotone" />
                </span>
                <span className="pt-[2px] text-[11px] font-semibold tracking-[0.18em] text-[#0b3b38]/35 transition-colors duration-500 group-hover:text-[#0b3b38]">
                  B
                </span>
              </div>
              <h3 className="relative mt-[24px] font-display text-[23px] leading-[1.15] tracking-[-0.35px] text-[#188f8b] md:text-[25px]">
                Mathematical privacy
              </h3>
              <p className="relative mt-[10px] text-[13.5px] leading-[1.55] tracking-[-0.1px] text-[#7c8f8d]">
                Differential privacy techniques keep industry benchmarks useful without ever tracing back to a specific user.
              </p>
            </div>
          </Reveal>
        </div>
      </Section>

      {/* BODY GRID */}
      <Section id="policy-body" narrow className="relative isolate pt-[0]!">
        <Reveal>
          <div className="mb-[32px] h-px w-full bg-gradient-to-r from-[#188f8b]/60 via-[#188f8b]/20 to-transparent" />
          <span className="mb-[20px] block text-[14px] font-semibold uppercase tracking-[0.18em] text-[#188f8b]">
            The details
          </span>
          <h2 className="mb-[48px] max-w-[640px] font-display text-[40px] leading-[0.95] tracking-[-1.28px] text-black md:mb-[56px] md:text-[56px]">
            What we do with your data
          </h2>
        </Reveal>

        <div className="grid grid-cols-1 gap-[14px] sm:grid-cols-2 lg:grid-cols-3">
          {SECTIONS.map((section, i) => (
            <PolicyCard
              key={section.id}
              section={section}
              delay={(i % 3) * 0.08}
            />
          ))}
        </div>
      </Section>
    </>
  );
}
